# Autobrowser TOML Configuration Example

# Global Variables - Define browser commands that can be reused in rules
[variables]
# Firefox with Work container for work-related URLs
work = "firefox 'ext+container:name=Work&url={}'"
# Regular Firefox for personal browsing
personal = "firefox {}"
# Chrome for development
dev = "google-chrome {}"

# Global Rules - Apply to all operating systems
[[rules]]
# Rule for opening Jira URLs in Work container
command = "work"
[rules.matchers]
url_regex = ".*jira.*"

[[rules]]
# Rule for opening GitHub in development browser
command = "dev"
[rules.matchers]
url_host = "github.com"

[[rules]]
# Rule for opening localhost URLs in development browser
command = "dev"
[rules.matchers]
url_host = "localhost"

# Global Default browser to use if no rules match
default = "personal"

# Linux-specific configuration
[linux]
variables = {
  # Linux-specific browser commands
  work = "firefox -p work {}"
}

# Linux-specific rules
[[linux.rules]]
command = "work"
[linux.rules.matchers]
app_class = "Slack"

[[linux.rules]]
command = "work"
[linux.rules.matchers]
app_class = "org.telegram.desktop"
app_title = ".*Work related group name.*"

# Darwin (macOS) specific configuration
[darwin]
variables = {
  # macOS-specific browser commands
  work = "open -a 'Zen' 'ext+container:name=Work&url={}'",
  personal = "open -a 'Safari' '{}'"
}

# macOS-specific rules
[[darwin.rules]]
command = "work"
[darwin.rules.matchers]
app_bundle_id = "com.tinyspeck.slackmacgap"

[[darwin.rules]]
command = "work"
[darwin.rules.matchers]
app_display_name = "Slack"

# macOS-specific default (overrides global default)
darwin.default = "personal"
