name: MacOS build

on:
  - push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'macos/go.mod'
        cache-dependency-path: 'macos/go.sum'


    - name: Build macos
      run: make build-macos
      
