name: Linux build

on:
  - push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'linux/go.mod'
        cache-dependency-path: 'linux/go.sum'

    - name: Build linux
      run: make build-linux
        
    - name: Install nFPM
      run: go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

    - name: Build rpm package
      run: nfpm pkg --packer rpm --target out/ -f linux/build/nfpm.yaml

    - name: Upload binary artifacts
      uses: actions/upload-artifact@v4
      with:
        path: out/* 